### ISSUE TITLE
有没有考虑过附件功能直接调用S3 Server？

### ISSUE THREAD

**Issue by xiongking** [soulteary/docker-outline#1]
这样应该可以少启一个docker。

**Comment by soulteary** [comment]
原因见 https://soulteary.com/2021/09/05/opensource-documentation-wiki-software-outline-part-1.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E9%80%89%E6%8B%A9%E4%BA%86-outline 中不足之处。

**Comment by soulteary** [comment]
官方下个版本据说将提供附件管理功能，不过不太推荐尝鲜。原因见：

https://soulteary.com/2021/09/11/opensource-documentation-wiki-software-outline-part-2.html
