### ISSUE TITLE
outline 漏了一个参数，少了不少功能

### ISSUE THREAD

**Issue by Xiechengqi** [soulteary/docker-outline#13]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/26536442/197825468-222f1519-8c14-45b1-9e75-6dcdfb00760c.png">

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/26536442/197825819-d2a18e0c-a788-4f56-8a85-4bf02212b971.png">

DEBUG 缺少 multiplayer，这样起来没有导入、导出等功能

**Comment by miaohf** [comment]
hi, xiechengqi,
你数据库没有报错么？
```
DatabaseError [SequelizeDatabaseError]: column team.slackId does not exist
```
