### ISSUE TITLE
ERROR: Version mismatch

### ISSUE THREAD

**Issue by Limezy** [soulteary/docker-outline#2]
Hi, thanks for this very useful project !
While trying to insall I got that mistake :

`ERROR: Version mismatch: file ./docker-compose.postgres.yml specifies version 3.0 but extension file ./docker-compose.sso.yml uses version 3.6`

How can I solve this ?

**Comment by Limezy** [comment]
I have changed all .yml files to version 3.6.
The setup goes well but I end up with two dockers that keep restarting : 

```      
Name                    Command                  State        Ports  
---------------------------------------------------------------------------
linx-server        /usr/local/bin/linx-server ...   Up (healthy)   8080/tcp
outline            docker-entrypoint.sh sh -c ...   Restarting             
outline-postgres   docker-entrypoint.sh postgres    Up (healthy)   5432/tcp
outline-redis      docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp
outline_minio      /usr/bin/docker-entrypoint ...   Restarting             
sso-server         docker-entrypoint.sh ./main      Up (healthy)   80/tcp 

Connection is refused !
Thanks in advance for your help

**Comment by soulteary** [comment]
My intuition should be related to the `compose` version. I've test it with docker-compose version 1.29+, macos and ubuntu 20.04.

According to the feedback of my readers, there are others who are up and running, but most of the users are Linux and mac users in my impression.

Hope it helps you.

**Comment by Limezy** [comment]
I'm using Debian 10 VPS. Let me try with Ubuntu as per your recommendation. Thanks

**Comment by Limezy** [comment]
Indeed after updating to docker-compose 1.29.2, no more mismatch problem and all dockers "healthy"
