### ISSUE TITLE
All containers up and healthy, can't access nothing

### ISSUE THREAD

**Issue by rgddev** [soulteary/docker-outline#3]
Hi.

  I followed all the steps and even tried to change the lab.com domain for another one I had accessible.
  The containers run and all of them are healthy. I can access them also (exec -it /bin/sh)

  But I can't access in any browser or computer any page (minio, outline, nothing)

  Host is a macOS (Intel)
  Docker updated today to last version
  All configuration of docker reset to default

What I can do to test using only localhost without any domain and send you the logs if I still can't access it?

**Comment by soulteary** [comment]
Hi, @rgddev .

I feel that you did not configure traefik.

In this example, Traefik is also used as the service gateway. If you are not familiar with Traefik, you can read the previous content to understand "Easier Ways to Use Traefik 2" and some practical examples of Traefik to deepen your understanding.

- https://soulteary.com/2020/12/02/easier-way-to-use-traefik-2.html
- https://soulteary.com/tags/traefik.html

**Comment by rgddev** [comment]
Hey @soulteary. I could get it working with Traefik, was using another way.

  But now, after enter username/password in SSO, I'm getting this (attach).
<img width="399" alt="Screen Shot 2021-09-10 at 18 24 58" src="https://user-images.githubusercontent.com/66889160/132919435-d9cfc702-00de-4ce2-8aca-828ea41c24ca.png">

  Even using Authy or Keepass as OTP (the initial code matches), I still can't login. I don't know if it's a Traefik problem as well.

**Comment by Limezy** [comment]
@rgddev could you please explain roughly how you did with Traefik ?
I can't see where I'm supposed to configure it ?
Thanks

**Comment by Limezy** [comment]
I'm using a dedicated vps with all urls (file.myurl.com, file-admin.myurl.com, sso.myurl.com, attachment.myurl.com, docs.myurl.com) pointing to it through the myurl.com DNS zone

**Comment by rgddev** [comment]
Sorry, @Limezy. I think because this is closed I didn't got any notification.
I did with Traefik, but can't use outline yet because the OTP error.
So probably the config is not going to be too much helpful...

**Comment by Limezy** [comment]
No worries !
