### ISSUE TITLE
Can't access from outside

### ISSUE THREAD

**Issue by Limezy** [soulteary/docker-outline#4]
Hi, I'm really sorry to disturb again.
I had a hard (and long) time trying to understand what's wrong in my setup but I failed !

I'm trying to install your self-hosted friendly outline version in a VPS I own, IPv4 `1.2.3.4`.

**DNS**
I own `domain.com` domain name.
I have setup my DNS zone :
docs.domain.com --> A 1.2.3.4
file.domain.com --> A 1.2.3.4
file-admin.domain.com --> A 1.2.3.4
sso.domain.com --> A 1.2.3.4
attachment.domain.com --> A 1.2.3.4

**Environment**
Ubuntu 20.04 with docker and docker-compose (1.29.2) as suggested

**Setup**
I have carefully followed all your steps
For the .env file I have only changed all urls to my own domain.com. Nothing else

**Installation and running**
Everything runs perfectly. All systems healthy. Nothing strange in the logs

**Usage**
Whatever url I use from all above urls, I get a connection refused from the server.
Seems like there is something to change in the Traefik labels, but I don't know why ?
I have tried to read https://soulteary.com/2020/12/02/traefik-2-basic-authorization-verification-part-1.html but I don't see what's different from the default setup of docker-outline ?

If you mind taking 2 minutes to give me another hint about where should I search to go forward that would be **really** helpful. Thanks in advance !

Moreover I've seen your PR in outline official repository. Many thanks for trying to help basic users like me self-hosting Outline software !

**Comment by soulteary** [comment]
Preliminary reasoning is that there is a problem with the traefik configuration.

I think maybe we should add a traefik configuration file to this project

**Comment by Limezy** [comment]
> I think maybe we should add a traefik configuration file to this project

That would be a very nice and welcomed help !
I can manage a server and do basic CLI stuff, but as a non-programmer things get hard for me quite fast, especially when it comes to network issues

**Comment by rgddev** [comment]
> Preliminary reasoning is that there is a problem with the traefik configuration.

I could setup the Traefik, but now I'm always getting OTP error as sent in #3 
Still can't use it.

**Comment by Limezy** [comment]
If you don't mind I would be interested to have a look at your config.
It will at least give me a first direction where to search !
Thanks

**Comment by Limezy** [comment]
Hi @soulteary, any guidance on where I should head over to better understand your use of traefik and what kind of setup I should prepare before running your script ? My usecase seems quite standard, I just need an https access from the outside :) 
Many thanks for your kind help

**Comment by soulteary** [comment]
For complete usage and configuration, see these three articles: https://suyang.wiki/runbook/outline/self-hosted.html
