### ISSUE TITLE
Can not use DB host var

### ISSUE THREAD

**Issue by rickywu** [soulteary/docker-outline#5]
outline.yml

```
      # DB
      - DATABASE_URL=${DATABASE_URL}
      - PGSSLMODE=${PGSSLMODE}
      - REDIS_URL=${REDIS_URL}
```

.env:
DOCKER_POSTGRES_HOST=ip.xxx
...
DATABASE_URL=postgres://${DOCKER_POSTGRES_USER}:${DOCKER_POSTGRES_PASS}@${DOCKER_POSTGRES_HOST}:5432/${DOCKER_POSTGRES_DBNAME}

outline容器启动报错
```
ERROR: connect ECONNREFUSED 127.0.0.1:5432

error Command failed with exit code 1.
```

**Comment by zhpjy** [comment]
update docker-compose to version 1.29.2
