### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by zdwork** [soulteary/docker-outline#8]
[+] Running 4/6
 ⠿ Container linx-server       Started                                                                                                                            1.0s
 ⠿ Container outline-postgres  Starting                                                                                                                           1.3s
 ⠿ Container sso-server        Started                                                                                                                            1.2s
 ⠿ Container outline           Started                                                                                                                            1.3s
 ⠿ Container outline_minio     Started                                                                                                                            1.3s
 ⠿ Container outline-redis     Starting                                                                                                                           1.3s
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/etc/timezone" to rootfs at "/etc/timezone" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by soulteary** [comment]
这个是因为你的操作系统缺少 /etc/timezone 这个文件，如果是mac/windows，直接删除掉这俩文件挂载就行了。

不过稳定的选择是使用 linux。
